---
# .goreleaser.yml
# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...

builds:
  - # Build configuration for the main yawn binary
    id: yawn
    # Path to main.go for the application.
    main: ./cmd/yawn/
    # Binary name.
    binary: yawn
    # Environment variables for the build.
    env:
      - CGO_ENABLED=0 # Build static binaries where possible
    # GOOS and GOARCH matrix.
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Optimized ldflags for performance and size
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    # Build flags for optimization
    flags:
      - -trimpath

# Disable archives - we want only binaries
archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

# Disable checksum generation as requested
checksum:
  disable: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge branch

release:
  # Repository configuration (usually auto-detected).
  # github:
  #   owner: Mayurifag
  #   name: yawn

  # Draft release? Set to true to create drafts instead of publishing directly.
  draft: false
  # Prerelease? Auto-detect based on tag format (e.g., v1.0.0-rc1).
  prerelease: auto

  # Optional: Name template for the release title.
  # name_template: "{{.Tag}} release"

  # Optional: Add extra files to the release assets.
  # extra_files:
  #   - glob: ./path/to/some/asset.deb
  #   - glob: ./other/asset.*
